config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :employees
  resources :addresses do
    collection do
      get :states
    end
  end
  resources :posts
  resources :tweets do
    resource :likes, only: [:create, :destroy]
    resource :retweets, only: [:create, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
end

app/models/employee.rb
class Employee < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search, against: [:name, :position, :office, :age, :start_date], using: { tsearch: { prefix: true } }
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
    @employees = @employees.search(params[:query]) if params[:query].present?
    @pagy, @employees = pagy(@employees.reorder(sort_column => sort_direction), items: params.fetch(:per_page, 10))
  end

  def sort_column
    Employee.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :position, :office, :age, :start_date)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>" class="table-row">
  <div class="my-5 table-cell pr-4">
    <%= employee.name %>
  </div>

  <div class="my-5 table-cell pr-4">
    <%= employee.position %>
  </div>

  <div class="my-5 table-cell pr-4">
    <%= employee.office %>
  </div>

  <div class="my-5 table-cell pr-4">
    <%= employee.age %>
  </div>

  <div class="my-5 table-cell pr-4">
    <%= employee.start_date %>
  </div>
</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee, class: "contents") do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :position %>
    <%= form.text_field :position, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :office %>
    <%= form.text_field :office, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :age %>
    <%= form.number_field :age, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing employee</h1>

  <%= render "form", employee: @employee %>

  <%= link_to "Show this employee", @employee, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to employees", employees_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/employees/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Employees</h1>
    <%= link_to 'New employee', new_employee_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <%= form_with url: "", method: :get, data: { turbo_frame: "employees", turbo_action: "advance" } do |form| %>
    Show <%= form.select :per_page, options_for_select([10, 25, 50, 100], selected: params[:per_page]), {}, {onchange: 'this.form.requestSubmit()'} %>
    Search <%= form.text_field(
      :query,
      {
        value: params[:query],
        class: "rounded-lg py-3 px-5 bg-gray-100 text-gray-600 font-medium", 
        placeholder: "Search by name",
        oninput: 'this.form.requestSubmit()'
      }
    )%>
  <% end %>
  <%= turbo_frame_tag "employees", class: "min-w-full" do %>
    <div class="table">
      <div class="table-header-group">
        <%= sort_link_to "Name", :name, class: "table-cell pr-4", data: { turbo_action: "advance" } %>
        <%= sort_link_to "Position", :position, class: "table-cell pr-4", data: { turbo_action: "advance" } %>
        <%= sort_link_to "Office", :office, class: "table-cell pr-4", data: { turbo_action: "advance" } %>
        <%= sort_link_to "Age", :age, class: "table-cell pr-4", data: { turbo_action: "advance" } %>
        <%= sort_link_to "Start Date", :start_date, class: "table-cell pr-4", data: { turbo_action: "advance" } %>
      </div>
      <%= render @employees %>
    </div>
  <% end %>

  <%== pagy_nav @pagy %>
</div>

app/views/employees/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New employee</h1>

  <%= render "form", employee: @employee %>

  <%= link_to 'Back to employees', employees_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/employees/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @employee %>

    <%= link_to 'Edit this employee', edit_employee_path(@employee), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this employee', employee_path(@employee), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to employees', employees_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>