config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :employees
  resources :addresses do
    collection do
      get :states
    end
  end
  resources :posts
  resources :tweets do
    resource :likes, only: [:create, :destroy]
    resource :retweets, only: [:create, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[ show edit update destroy ]

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1 or /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to address_url(@address), notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to address_url(@address), notice: "Address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def states
    @target = params[:target]
    @states = CS.states(params[:country]).invert
    respond_to do |format|
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:country, :state)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_address.html.erb
<div id="<%= dom_id address %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Country:</strong>
    <%= address.country %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">State:</strong>
    <%= address.state %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this address", address, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this address', edit_address_path(address), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/addresses/_form.html.erb
<%= form_with(model: address, class: "contents") do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div data-controller="select" data-select-url-value="<%= states_addresses_path %>" data-select-param-value="country">
    <div class="my-5">
      <%= form.label :country %>
      <%= form.select(
        :country,
        CS.countries.invert,
        { prompt: "Select a country" },
        {
          class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full",
          data: { action: "change->select#change" }
        }
      ) %>
    </div>
  

    <div class="my-5">
      <%= form.label :state %>
      <%= form.select(
        :state,
        [],
        { prompt: "Select a State" },
        { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { select_target: 'select' } }
      ) %>
    </div>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing address</h1>

  <%= render "form", address: @address %>

  <%= link_to "Show this address", @address, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to addresses", addresses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/addresses/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Addresses</h1>
    <%= link_to 'New address', new_address_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="addresses" class="min-w-full">
    <%= render @addresses %>
  </div>
</div>

app/views/addresses/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New address</h1>

  <%= render "form", address: @address %>

  <%= link_to 'Back to addresses', addresses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/addresses/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @address %>

    <%= link_to 'Edit this address', edit_address_path(@address), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this address', address_path(@address), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to addresses', addresses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/addresses/states.turbo_stream.erb
<%= turbo_stream.update @target do %>
  <%= options_for_select(@states) %>
<% end %>